{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-api",
    "version": "5.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "nl5ignh23jdd7pqfnyu5j6hawe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.7.0.jar",
          "url": "junit-jupiter-api-5.7.0.jar",
          "size": 174598,
          "sha512": "b5551a908ccca41418ea2502d29840d302e8d64ec9f6ff1aeba316568e6ad357dd33a7973d28d836796cf40be304afc7b362bc5ad7eed1fdb638d43c8969a93b",
          "sha256": "b03f78e0daeed2d77a0af9bcd662b4cdb9693f7ee72e01a539b508b84c63d182",
          "sha1": "b25f3815c4c1860a73041e733a14a0379d00c4d5",
          "md5": "e8567a8fe9ea0fa92b4da7a25f0c572c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.7.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.7.0.jar",
          "url": "junit-jupiter-api-5.7.0.jar",
          "size": 174598,
          "sha512": "b5551a908ccca41418ea2502d29840d302e8d64ec9f6ff1aeba316568e6ad357dd33a7973d28d836796cf40be304afc7b362bc5ad7eed1fdb638d43c8969a93b",
          "sha256": "b03f78e0daeed2d77a0af9bcd662b4cdb9693f7ee72e01a539b508b84c63d182",
          "sha1": "b25f3815c4c1860a73041e733a14a0379d00c4d5",
          "md5": "e8567a8fe9ea0fa92b4da7a25f0c572c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.7.0-javadoc.jar",
          "url": "junit-jupiter-api-5.7.0-javadoc.jar",
          "size": 1016842,
          "sha512": "0d09e0010e66723da53e84c2414f921eb10ee4f575e6bd8f0d95b91745050f2f30c2381dc1dfdd2ae647c4ffd2da93c049dadd80fee58ef245d32eb1ee82e0ba",
          "sha256": "4fcfb490fa1a38615384b2a80ccbf091909a80651c8ce6b3662b685961aa7ac4",
          "sha1": "bfd92c400ba91f50bff949ca4f82c76e023e2dfa",
          "md5": "fd040662605ff3ccb1eac5677a1c6b59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.7.0-sources.jar",
          "url": "junit-jupiter-api-5.7.0-sources.jar",
          "size": 172865,
          "sha512": "7cff583c95c2f1a3c12b81b92f153db9ca4751b6ee0ae10bcb1bb50f1a16f4f4283254d175b8cb8558da2e112fd7b2ba17c34c9190b348e032181ebeeb47a532",
          "sha256": "44cbc734e5052e2e15efd1572d9fe2e9c6c43a63075014499936bd3201d41002",
          "sha1": "388560dc9aa3c479df4e3effce036646c8b89719",
          "md5": "ba2ab128ff147e75662b97a9bbc79dc0"
        }
      ]
    }
  ]
}
